class UserError(Exception):
    pass


class NoRecordFound(Exception):
    pass
